export default [
    {
        key:"recent",
        title:"最近编辑",
        to:"/dashboard"
    },
    {
        key:"article",
        title:"我的文章",
        to:"/dashboard/article"
    },
    {
        key:"question",
        title:"我的提问",
        to:"/dashboard/question"
    },
    {
        key:"answer",
        title:"我的回答",
        to:"/dashboard/answer"
    },
    {
        key:"finance",
        title:"我的资产",
        to:"/dashboard/finance"
    },
    {
        key:"divider"
    },
    {
        key:"follows",
        title:"关注",
        to:"/dashboard/follows"
    },
    {
        key:"collections",
        title:"收藏",
        to:"/dashboard/collections"
    },
    {
        key:"history",
        title:"最近浏览",
        to:"/dashboard/history"
    }
]