export default [
    {
        key:"recent",
        title:"最近编辑",
        to:"/user/dashboard"
    },
    {
        key:"article",
        title:"我的文章",
        to:"/user/dashboard/article"
    },
    {
        key:"question",
        title:"我的提问",
        to:"/user/dashboard/question"
    },
    {
        key:"answer",
        title:"我的回答",
        to:"/user/dashboard/answer"
    },
    {
        key:"divider"
    },
    {
        key:"follows",
        title:"关注",
        to:"/user/dashboard/follows"
    },
    {
        key:"collections",
        title:"收藏",
        to:"/user/dashboard/collections"
    },
    {
        key:"history",
        title:"最近浏览",
        to:"/user/dashboard/history"
    }
]